name: Codety
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
jobs:
  Codety_Static_Code_Analysis:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    container:
      image: codetyio/codety:0.002
  
    steps:
      
      - run: codety
        
